Fix aws-ts examples
The lambda examples started failing after `@aws-sdk/credential-provider-node@3.972.56` changed credential providers from lazy `await import(...)` loading to eager `require(...)` references https://github.com/aws/aws-sdk-js-v3/pull/8103. This caused the function serialization to try to serialize all of this, hitting a native `call` function and failing

```
 error: error serializing property "code":
  Error serializing 'async (...) => ...'

  captured
    variable 's3sdk' which indirectly referenced
      function 'S3'
        function 'S3Client'
          ...
            function 'join'
              ...
                'ObjectPrototypeHasOwnProperty'
                  function 'bound call': which could not be serialized because
                    it was a native code function.
```

Fix this by moving the require into the lambda, so it’s not part of the closure.

The nextjs example required updated peer dependencies.