Prevent panic when response from server is nil
When trying to `defer resp.body.Close()` when the resp or resp.body
is nil then we are getting a panic in our tests as follows:

```
    --- FAIL: TestExamples/azure-ts-appservice-docker (922.36s)
        program.go:423: panic testing /home/travis/gopath/src/github.com/pulumi/examples/azure-ts-appservice-docker: runtime error: invalid memory address or nil pointer dereference
```