Use provided.al2 AWS Go Lambda runtime to fix build process (#1677)(Created for Tests to run) #1770 (#1771)
## What?

This PR updates this example to use the now required `provided.al2` AWS
Go Lambda runtime, along with necessary related changes.

## Why?

Running `pulumi up` in this example results in the following error:

```
InvalidParameterValueException: The runtime parameter of go1.x is no longer supported for creating or updating AWS Lambda functions. 
We recommend you use a supported runtime while creating or updating functions.
```

`go1.x` runtime Lambdas [must now be

migrated](https://docs.aws.amazon.com/lambda/latest/dg/lambda-golang.html#golang-al1)
to `provided.al2023` or `provided.al2` runtimes.

Co-authored-by: Luke Rogerson <contact@lukerogerson.me>