Ensure DnsRecord depends on domain record in do-py-k8
This is consistent with examples from other languages: see https://github.com/pulumi/examples/blob/master/digitalocean-cs-k8s/KubernetesStack.cs#L98 for example.

Without this dependency, the example occasionally produces the following error:

```
Diagnostics:
  pulumi:pulumi:Stack (digitalocean-py-k8s-dev):
    error: update failed

  digitalocean:index:DnsRecord (do-domain-name):
    error: Failed to create record: POST https://api.digitalocean.com/v2/domains/<REDACTED>/records: 404 The resource you were accessing could not be found.
```