Update first-party Pulumi dependencies (minor) (#2476)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [@pulumi/kubernetes](https://pulumi.com)
([source](https://redirect.github.com/pulumi/pulumi-kubernetes)) |
dependencies | minor | [`4.23.0` ->
`4.24.1`](https://renovatebot.com/diffs/npm/@pulumi%2fkubernetes/4.23.0/4.24.1)
|
|
[github.com/pulumi/pulumi-kubernetes/sdk/v4](https://redirect.github.com/pulumi/pulumi-kubernetes)
| require | minor | `v4.23.0` -> `v4.24.1` |
|
[pulumi-kubernetes](https://redirect.github.com/pulumi/pulumi-kubernetes)
| | minor | `>=4.23.0,<4.24.0` -> `>=4.24.1,<4.25.0` |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>pulumi/pulumi-kubernetes (@&#8203;pulumi/kubernetes)</summary>

###
[`v4.24.1`](https://redirect.github.com/pulumi/pulumi-kubernetes/releases/tag/v4.24.1)

[Compare
Source](https://redirect.github.com/pulumi/pulumi-kubernetes/compare/v4.24.0...v4.24.1)

##### Fixed

- Fixed a regression of
[#&#8203;2943](https://redirect.github.com/pulumi/pulumi-kubernetes/pull/2943)
which could cause Deployments to erroneously report diffs.

##### Changed

- Upgraded `helm.sh/helm` to v3.18.6.
([https://github.com/pulumi/pulumi-kubernetes/issues/3969](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3969))

###
[`v4.24.0`](https://redirect.github.com/pulumi/pulumi-kubernetes/blob/HEAD/CHANGELOG.md#4240-November-5-2025)

[Compare
Source](https://redirect.github.com/pulumi/pulumi-kubernetes/compare/v4.23.0...v4.24.0)

##### Added

- Added a `plainHttp` option to the `v4.Chart` resource.
([https://github.com/pulumi/pulumi-kubernetes/issues/3250](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3250))

##### Changed

-   The `pulumi.com/waitFor` annotation now uses an
[RFC9535](https://www.rfc-editor.org/rfc/rfc9535.html)-compliant
JSONPath
    parser. This makes it possible to wait for more complex scenarios.

    For example:

- To wait for a Pod's `status.phase` to be "Running" or "Succeeded":

`pulumi.com/waitFor: "jsonpath={.status[?@&#8203; == 'Running' ||
@&#8203; == 'Succeeded' ]}"`

- To wait for for an object to have a "Failed" *or* "Complete" condition
with
        a "True" value:

`pulumi.com/waitFor:
"jsonpath={.conditions[?(@&#8203;.type=='Failed'||@&#8203;.type=='Complete')].status}=True`

(Tools like [jsonpath.com](https://jsonpath.com) are very helpful for
    ensuring your JSONPath expression works as expected.)

Importantly, please note that `kubectl wait --for=jsonpath=...` supports
only
a *subset* of RFC9535. This means some complex `waitFor` annotations
will not
    be reproducible with `kubectl`.

Existing expressions should continue to work normally with one notable
exception: a selector like `.items[]` now requires an explicit wildcard,
i.e.
    `.items[*]`.

As a reminder, the `pulumi.com/waitFor` annotation is experimental and
subject to change. Similarly, RFC9535 is still only *proposed* and may
also
    change in the future.

-   `enableConfigMapMutable` and `enableSecretMutable` are now stable.

[https://github.com/pulumi/pulumi-kubernetes/pull/3886](https://redirect.github.com/pulumi/pulumi-kubernetes/pull/3886)3886)

##### Fixed

- Helm resources all now use the correct `registry/config.json` file for
credentials. For backward-compatibility `registry.json` is preferred if
it
exist[https://github.com/pulumi/pulumi-kubernetes/issues/3606](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3606)3606)

- Fixed an issue where deletions could take longer than necessary.
([https://github.com/pulumi/pulumi-kubernetes/issues/3317](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3317))

- Significantly reduced memory usage.
([https://github.com/pulumi/pulumi-kubernetes/issues/3713](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3713))

- Fixed incorrect deprecation warnings for VolumeAttributesClass.
([https://github.com/pulumi/pulumi-kubernetes/issues/3772](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3772))

-   SecretPatch inputs are now automatically marked as secret.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 10am every weekday" (UTC),
Automerge - Monday through Friday ( * * * * 1-5 ) (UTC).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4yNjQuMCIsInVwZGF0ZWRJblZlciI6IjM5LjI2NC4wIiwidGFyZ2V0QnJhbmNoIjoibWFzdGVyIiwibGFiZWxzIjpbImRlcGVuZGVuY2llcyIsImltcGFjdC9uby1jaGFuZ2Vsb2ctcmVxdWlyZWQiXX0=-->

Co-authored-by: pulumi-renovate[bot] <189166143+pulumi-renovate[bot]@users.noreply.github.com>